server:
  port: 8080
spring:
  application:
    name: freemarker-demo
  freemarker:
    cache: false
    charset: utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
  resources:
    static-locations: classpath:/static/# 应用服务 WEB 访问端口
